language: node_js
node_js:
  - 12.1.0
cache: npm
stages:
  - test
  - publish
jobs:
  include:
    - stage: test
      name: '🗜️Test & lint'
      script: npm run lint && npm run test:coverage
after_success:
  - npx codecov
